networks:
  kws_main:
    driver: bridge
  kws_ins_s:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.0.0/24
        - gateway: 172.35.0.1
  
volumes:
  #Main
  postgres_db_data_kws:
  redis_db_data_kws:
  mq_kws:

  #Services
  postgres_db_service_data:

services:
  # ------------------------------Main-------------------------------
  postgres:
    image: postgres:alpine
    container_name: postgres_db_kws
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBNAME}
    volumes:
      - postgres_db_data_kws:/var/lib/postgresql/data:rw
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - kws_main
  
  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    container_name: mq_q_kws
    restart: always
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${MQ_PASSWORD}
    ports:
      - "${MQ_SERVER_PORT}:${MQ_SERVER_PORT}"
      - "${MQ_UI_PORT}:${MQ_UI_PORT}"
    volumes:
      - mq_kws:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kws_main

  redis:
    image: redis:alpine
    container_name: redis_db_kws
    volumes:
      - redis_db_data_kws:/data:rw
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always
    networks:
      - kws_main

  kws_gateway:
    image: golang:latest
    container_name: kws_gateway
    privileged: true
    volumes:
      - ./src/:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/wireguard:/etc/wireguard:ro
    network_mode: "host"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    working_dir: /app/data/cmd
    command: sh -c "apt-get update && apt-get install -y uuid-runtime && go run ."

  # ------------------------------Services-------------------------------
  proxy:
    image: golang:latest
    container_name: proxy.kws.services
    volumes:
      - ./proxy/:/app/data
    networks:
      kws_ins_s:
        ipv4_address: 172.35.0.2
    ports:
      - "9000:9000"
    working_dir: /app/data
    command: sh -c "go run ."
  
  postgres_service:
    image: postgres:alpine
    container_name: postgres.kws.services
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_SERVICE_USERNAME}
      POSTGRES_PASSWORD: ${PG_SERVICE_PASSWORD}
    volumes:
      - postgres_db_service_data:/var/lib/postgresql/data:rw
    networks:
      kws_ins_s:
        ipv4_address: 172.35.0.3
