package status

const (
	USER_NAME_INVALID = "0"
	USER_NOT_VERIFIED = "1"
	WRONG_CREDENTIALS = "2"

	CONTAINER_ALREADY_RUNNING   = "3"
	CONTAINER_ALREADY_EXISTS    = "4"
	CONTAINER_NOT_FOUND_TO_STOP = "5"

	// DB errors
	CONTAINER_START_FAILED = "6"
)
