package status

const (
	USER_NAME_INVALID = "0"
	USER_NOT_VERIFIED = "1"
	WRONG_CREDENTIALS = "2"

	CONTAINER_ALREADY_RUNNING     = "3"
	CONTAINER_ALREADY_EXISTS      = "4"
	CONTAINER_NOT_FOUND_TO_STOP   = "5"
	CONTAINER_NOT_FOUND_TO_DELETE = "6"
	VOLUME_NOT_FOUND              = "7"

	// DB errors
	CONTAINER_START_FAILED = "8"
)
