events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server_names_hash_bucket_size 128;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    sendfile        on;

    include /etc/nginx/conf.d/*.conf;
}
