package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// writeKWSConfig writes the KWSConfig to kws_config.yaml.
func writeKWSConfig(cfg *KWSConfig, path string) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	header := "# KWS Configuration\n# Generated by kws_install\n# Edit values as needed, then run 'make up' to start.\n\n"

	if err := os.WriteFile(path, []byte(header+string(data)), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}

	return nil
}

// writeEnvFile writes the .env file for Docker Compose and the Go application.
func writeEnvFile(envCfg *EnvConfig, path string) error {
	content := fmt.Sprintf(`# ------------------------------Main-------------------------------
# Postgres
DB_USERNAME=%s
DB_PASSWORD=%s
DB_DBNAME=%s
DB_HOST=%s
DB_PORT=%s

# Redis
REDIS_HOST=%s
REDIS_PORT=%s
REDIS_PASSWORD=%s

# Gmail
GMAIL_APP_PASSWORD=%s
GMAIL_ADDRESS=%s
SMTP_HOST=%s
SMTP_PORT=%s

# Environment
ENV=%s

# RabbitMq
MQ_USER=%s
MQ_PASSWORD=%s
MQ_SERVER_PORT=%s
MQ_UI_PORT=%s
MQ_HOST=%s

# Wireguard
WG_PRIVATE_KEY=%s
WG_PUBLIC_KEY=%s

# Compose network overrides
SERVICES_SUBNET=%s
SERVICES_GATEWAY=%s
PG_SERVICE_IP=%s
ADMINER_IP=%s

# Bridge attach list (space-separated container:bridge:ipcidr triples)
ATTACH_SERVICES=%s


# ------------------------------Services-------------------------------
# Postgres
PG_SERVICE_USERNAME=%s
PG_SERVICE_PASSWORD=%s
PG_SERVICE_HOST=%s
PG_SERVICE_PORT=%s
PG_SERVICE_DB=%s
`,
		envCfg.DBUsername, envCfg.DBPassword, envCfg.DBName, envCfg.DBHost, envCfg.DBPort,
		envCfg.RedisHost, envCfg.RedisPort, envCfg.RedisPassword,
		envCfg.GmailAppPassword, envCfg.GmailAddress, envCfg.SMTPHost, envCfg.SMTPPort,
		envCfg.Env,
		envCfg.MQUser, envCfg.MQPassword, envCfg.MQServerPort, envCfg.MQUIPort, envCfg.MQHost,
		envCfg.WGPrivateKey, envCfg.WGPublicKey,
		envCfg.ServicesSubnet, envCfg.ServicesGateway, envCfg.PGServiceIP, envCfg.AdminerIP,
		envCfg.AttachServices,
		envCfg.PGServiceUsername, envCfg.PGServicePassword, envCfg.PGServiceHost, envCfg.PGServicePort, envCfg.PGServiceDB,
	)

	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}

	return nil
}

// generateNginxMainConf generates the main.conf nginx site config.
func generateNginxMainConf(cfg *KWSConfig, path string) error {
	tmplStr := `# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name {{ .Domain }} www.{{ .Domain }} *.{{ .Domain }};
    return 301 https://$host$request_uri;
}

# HTTPS Server Block
server {
    listen 443 ssl;
    server_name {{ .Domain }} www.{{ .Domain }};

    ssl_certificate {{ .SSL.CertPath }};
    ssl_certificate_key {{ .SSL.KeyPath }};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://127.0.0.1:{{ .Server.GatewayPort }};

        # WebSocket headers
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Normal headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_buffering off;
    }
}
`
	return writeTemplate(tmplStr, cfg, path)
}

// generateNginxDefaultConf generates the 00-default.conf nginx fallback config.
func generateNginxDefaultConf(cfg *KWSConfig, path string) error {
	tmplStr := `# HTTP fallback
server {
    listen 80 default_server;
    server_name _;
    return 444;
}

# HTTPS fallback
server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate     {{ .SSL.CertPath }};
    ssl_certificate_key {{ .SSL.KeyPath }};

    return 444;
}
`
	return writeTemplate(tmplStr, cfg, path)
}

// generateDnsmasqConf generates dnsmasq.conf with proper service IPs.
func generateDnsmasqConf(cfg *KWSConfig, path string) error {
	ipByContainer := make(map[string]string)
	for _, ba := range cfg.Services.BridgeAttach {
		ipByContainer[ba.Container] = strings.Split(ba.IPCIDR, "/")[0]
	}

	pgIP := ipByContainer[cfg.Services.PostgresHostname]
	if pgIP == "" {
		pgIP = "172.30.0.2"
	}
	adminerIP := ipByContainer[cfg.Services.AdminerHostname]
	if adminerIP == "" {
		adminerIP = "172.30.0.3"
	}

	content := fmt.Sprintf(`listen-address=0.0.0.0
bind-dynamic
no-hosts
no-resolv
server=8.8.8.8
server=1.1.1.1
address=/%s/%s
address=/%s/%s
`, cfg.Services.PostgresHostname, pgIP, cfg.Services.AdminerHostname, adminerIP)

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}

	return nil
}

// generateComposeOverrides generates the compose.yaml with config-driven subnet values.
// Rather than templating the entire compose file, we generate a .env that compose references.
// The compose.yaml already uses ${VAR} syntax for most things via the .env file.
// We add the new network subnet vars to the .env.

// writeTemplate is a helper to parse and execute a Go template to a file.
func writeTemplate(tmplStr string, data interface{}, path string) error {
	tmpl, err := template.New("file").Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create %s: %w", path, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

func generateAnsibleInventory(ans *AnsibleConfig, cfg *KWSConfig, projectRoot string) (string, error) {
	ansibleDir := filepath.Join(projectRoot, "ansible")
	os.MkdirAll(ansibleDir, 0755)

	invPath := filepath.Join(ansibleDir, "inventory")

	content := fmt.Sprintf(`# KWS Ansible Inventory — Generated by kws_install
# Do not commit this file (it is gitignored).

[kws_hosts]
kws-server ansible_host=%s ansible_user=%s ansible_ssh_private_key_file=%s

[kws_hosts:vars]
kws_domain=%s
kws_public_ip=%s
wg_interface=%s
wg_address=%s
wg_listen_port=%d
wg_private_key=%s
wg_public_key=%s
lxd_bridge_name=%s
lxd_bridge_subnet=%s
lxd_bridge_gateway=%s
`,
		ans.TargetIP, ans.SSHUser, ans.SSHKeyPath,
		cfg.Domain, cfg.PublicIP,
		cfg.Wireguard.InterfaceName, cfg.Wireguard.Address, cfg.Wireguard.ListenPort,
		ans.WGPrivKey, ans.WGPubKey,
		cfg.Network.LXDBridgeName, cfg.Network.LXDBridgeSubnet, cfg.Network.LXDBridgeGateway,
	)

	if err := os.WriteFile(invPath, []byte(content), 0600); err != nil {
		return "", fmt.Errorf("failed to write inventory: %w", err)
	}

	return invPath, nil
}
